### ISSUE TITLE
xDscDiagnostics should also collect logs generated on the pull server.

### ISSUE THREAD

**Issue by nitinbps** [PowerShell/xDscDiagnostics#24]

**Comment by nitinbps** [comment]
Logs can be obtained using:
Get-WinEvent -LogName
"Microsoft-Windows-Powershell-DesiredStateConfiguration-PullServer/Operational"
Get-WinEvent -LogName
"Microsoft-Windows-ManagementOdataService/Operational"

**Comment by Indhukrishna** [comment]
This is currently possible. I added this functionality as part of this commit - https://github.com/PowerShell/xDscDiagnostics/commit/5b467b1106fb204e9a7226d15263941758dedb2e

**Comment by Indhukrishna** [comment]
We do not collect  Odata logs currently.I will fix this part.

**Comment by Indhukrishna** [comment]
#27

**Comment by kwirkykat** [comment]
Fixed by #27
