### ISSUE TITLE
Updated 2.4.78 version missing 4th versioning number.

### ISSUE THREAD

**Issue by Slade122** [PowerShell/xDscDiagnostics#34]
When adding the new build 2.4.78, the 4th versioning number is missing, breaking the ability to import the module or for the module to be picked up automatically by auto-loading.

In order to correct the issue, .0 needs to be added to the build number, making the complete path as follows.

C:\Program Files\WindowsPowerShell\Modules\xDscDiagnostics\2.4.78.0

**Comment by kwirkykat** [comment]
@Slade122 The [currently released version](https://www.powershellgallery.com/packages/xDscDiagnostics/2.4.0.0) on PSGallery is 2.4.0.0. Are you pulling a build from AppVeyor?

**Comment by johlju** [comment]
Closing this as not fixed due to lack of response. Please reopen or comment if this was closed in error.
